### ISSUE TITLE
Tidy up image names

### ISSUE THREAD

**Issue by berry120** [quelea-projection/quelea-projection.github.io#2]
You'll notice that all the images [in the docs folder](https://github.com/quelea-projection/quelea-projection.github.io/tree/master/docs) have been imported from Mediawiki, and don't have descriptive names. Feel free to update them so these names match what the screenshot represents, but note that if you do so, you'll need to make sure the name is also updated in the corresponding markdown file that references the image! (We don't want a load of broken images to suddenly appear.) 👍 

PR's for this are very welcome, even if they just rename a single image.

**Comment by aayushbisen** [comment]
I'll do it.

**Comment by berry120** [comment]
Thanks! :+1:

**Comment by berry120** [comment]
Whoops, ignore that.

**Comment by Jobayer-Ahmed** [comment]
I'll Fix it...

**Comment by berry120** [comment]
Looks like this one has already been taken, but you're welcome to make any other improvements you can find to the docs :)

**Comment by Ananthavijay** [comment]
Can i work on this @berry120

**Comment by roxyd** [comment]
i did this for themes.md and submitted a PR: https://github.com/quelea-projection/quelea-projection.github.io/pull/7

**Comment by berry120** [comment]
Thanks, that's accepted. Other contributions for other pages also welcome.
