### ISSUE TITLE
Link to Google Forum is broken

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/quelea-projection.github.io#9]
I attempted to follow the link to the Google Forum page, and it showed a message saying that either the group doesn't exist or I am lacking permission to view it and to contact the owner about it.

**Comment by ArvidNy** [comment]
You're right, we moved the discussion over to this website: https://quelea.discourse.group/ I've updated all the pages that linked to the old discussion group. Thanks for reporting it!
